-- Naqla: full database setup for a NEW Supabase project.
-- GENERATED by scripts/bundle-migrations.mjs from supabase/migrations. Do not edit by hand.
-- Contains 17 migrations in order. Paste all of it into Supabase > SQL Editor and click Run.
-- Safe to re-run on the same project.

-- ============================================================
-- 001_initial_schema.sql
-- ============================================================
-- Hunda Design — Supabase initial database schema
-- Run once from Supabase Dashboard > SQL Editor > New query > Run

begin;

create extension if not exists pgcrypto;

-- ---------- Helpers ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.normalize_activation_code(p_code text)
returns text
language sql
immutable
strict
as $$
  select upper(regexp_replace(trim(p_code), '[^A-Za-z0-9]', '', 'g'));
$$;

-- ---------- Core tables ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  experience text,
  phone text,
  avatar_path text,
  role text not null default 'student' check (role in ('student', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key default 'public',
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  price numeric(12,2) not null default 0 check (price >= 0),
  paypal_price_usd numeric(12,2) check (paypal_price_usd is null or paypal_price_usd >= 0),
  trc20_price_usdt numeric(12,2) check (trc20_price_usdt is null or trc20_price_usdt >= 0),
  published boolean not null default true,
  featured boolean not null default false,
  thumbnail_path text,
  thumbnail_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lectures (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  title text not null,
  description text not null default '',
  duration_text text not null default '',
  sort_order integer not null default 1 check (sort_order > 0),
  is_free boolean not null default false,
  published boolean not null default true,
  video_path text,
  video_name text,
  thumbnail_path text,
  thumbnail_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (course_id, sort_order)
);

create table if not exists public.materials (
  id uuid primary key default gen_random_uuid(),
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  title text not null,
  file_path text not null,
  file_name text,
  file_size bigint check (file_size is null or file_size >= 0),
  mime_type text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete restrict,
  provider text not null check (provider in ('paymob','fawry','paypal','instapay','vodafone_cash','trc20','manual')),
  status text not null default 'pending' check (status in ('created','pending','awaiting_transfer','paid','failed','cancelled','refunded')),
  amount numeric(12,2) not null check (amount >= 0),
  currency text not null default 'EGP',
  external_reference text,
  provider_order_id text,
  payment_proof_path text,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activation_codes (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses(id) on delete cascade,
  code_hash text not null unique,
  code_preview text not null,
  is_active boolean not null default true,
  expires_at timestamptz,
  used_by uuid references auth.users(id) on delete set null,
  used_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check ((used_at is null and used_by is null) or (used_at is not null and used_by is not null))
);

create table if not exists public.enrollments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  source text not null default 'manual' check (source in ('activation_code','payment','manual','gift')),
  payment_id uuid references public.payments(id) on delete set null,
  activation_code_id uuid references public.activation_codes(id) on delete set null,
  active boolean not null default true,
  enrolled_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, course_id)
);

create table if not exists public.lecture_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  completed boolean not null default false,
  watched_seconds integer not null default 0 check (watched_seconds >= 0),
  last_position_seconds integer not null default 0 check (last_position_seconds >= 0),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, lecture_id)
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  student_name text not null,
  experience text not null default 'مبتدئ',
  title text not null,
  description text not null default '',
  image_path text not null,
  image_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  lecture_id uuid not null references public.lectures(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, lecture_id)
);

create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  certificate_code text not null unique,
  issued_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (user_id, course_id)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- ---------- Useful indexes ----------
create index if not exists idx_courses_published on public.courses (published, featured);
create index if not exists idx_lectures_course_order on public.lectures (course_id, sort_order);
create index if not exists idx_materials_lecture on public.materials (lecture_id);
create index if not exists idx_enrollments_user_active on public.enrollments (user_id, active);
create index if not exists idx_projects_status_created on public.projects (status, created_at desc);
create index if not exists idx_payments_user_created on public.payments (user_id, created_at desc);
create index if not exists idx_activation_codes_course on public.activation_codes (course_id, is_active);
create index if not exists idx_notifications_user_created on public.notifications (user_id, created_at desc);

-- ---------- Auth profile trigger ----------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1))
  )
  on conflict (id) do update set
    email = excluded.email,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

-- Backfill profiles for any existing Auth users.
insert into public.profiles (id, email, display_name)
select id, email, coalesce(raw_user_meta_data ->> 'display_name', raw_user_meta_data ->> 'full_name', split_part(coalesce(email, ''), '@', 1))
from auth.users
on conflict (id) do update set email = excluded.email;

-- ---------- Authorization helpers ----------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active = true
  );
$$;

create or replace function public.can_access_course(p_course_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin() or exists (
    select 1 from public.enrollments
    where user_id = auth.uid() and course_id = p_course_id and active = true
  );
$$;

create or replace function public.can_access_lecture(p_lecture_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.lectures l
    where l.id = p_lecture_id
      and l.published = true
      and (l.is_free = true or public.can_access_course(l.course_id))
  );
$$;

create or replace function public.can_access_lecture_path(p_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.lectures l
    where l.video_path = p_path and public.can_access_lecture(l.id)
  );
$$;

create or replace function public.can_access_material_path(p_path text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.materials m
    where m.file_path = p_path and public.can_access_lecture(m.lecture_id)
  );
$$;

-- Prevent users from promoting themselves.
create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role
     and coalesce(auth.role(), '') <> 'service_role'
     and not public.is_admin() then
    raise exception 'Only an admin can change user roles';
  end if;
  return new;
end;
$$;

drop trigger if exists prevent_role_escalation_trigger on public.profiles;
create trigger prevent_role_escalation_trigger
before update on public.profiles
for each row execute function public.prevent_role_escalation();

-- ---------- Single-use activation code RPCs ----------
-- Drop first: later migrations change the parameter defaults, which CREATE OR REPLACE cannot undo.
drop function if exists public.generate_activation_codes(uuid, integer, timestamptz);
create or replace function public.generate_activation_codes(
  p_course_id uuid,
  p_quantity integer default 1,
  p_expires_at timestamptz default null
)
returns table (id uuid, code text, code_preview text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  i integer;
  v_code text;
  v_hash text;
  v_id uuid;
  v_preview text;
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;
  if p_quantity < 1 or p_quantity > 500 then
    raise exception 'Quantity must be between 1 and 500';
  end if;
  if not exists (select 1 from public.courses where courses.id = p_course_id) then
    raise exception 'Course not found';
  end if;

  for i in 1..p_quantity loop
    loop
      v_code := 'HD-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4)) || '-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4));
      v_hash := encode(digest(public.normalize_activation_code(v_code), 'sha256'), 'hex');
      v_preview := 'HD-****-' || right(v_code, 4);
      begin
        insert into public.activation_codes (course_id, code_hash, code_preview, expires_at, created_by)
        values (p_course_id, v_hash, v_preview, p_expires_at, auth.uid())
        returning activation_codes.id into v_id;
        exit;
      exception when unique_violation then
        -- Extremely unlikely; generate another random code.
      end;
    end loop;

    id := v_id;
    code := v_code;
    code_preview := v_preview;
    return next;
  end loop;
end;
$$;

create or replace function public.redeem_activation_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user uuid := auth.uid();
  v_hash text;
  v_code public.activation_codes%rowtype;
  v_course public.courses%rowtype;
  v_already_enrolled boolean;
begin
  if v_user is null then
    raise exception 'Authentication required';
  end if;

  v_hash := encode(digest(public.normalize_activation_code(p_code), 'sha256'), 'hex');

  select * into v_code
  from public.activation_codes
  where code_hash = v_hash
  for update;

  if not found then raise exception 'Invalid activation code'; end if;
  if not v_code.is_active then raise exception 'Activation code is disabled'; end if;
  if v_code.used_at is not null then raise exception 'Activation code was already used'; end if;
  if v_code.expires_at is not null and v_code.expires_at <= now() then raise exception 'Activation code has expired'; end if;

  select * into v_course from public.courses where id = v_code.course_id;
  if not found or not v_course.published then raise exception 'Course is not available'; end if;

  select exists (
    select 1 from public.enrollments
    where user_id = v_user and course_id = v_code.course_id and active = true
  ) into v_already_enrolled;

  insert into public.enrollments (user_id, course_id, source, activation_code_id, active)
  values (v_user, v_code.course_id, 'activation_code', v_code.id, true)
  on conflict (user_id, course_id)
  do update set active = true, source = 'activation_code', activation_code_id = excluded.activation_code_id, updated_at = now();

  update public.activation_codes
  set used_by = v_user, used_at = now(), is_active = false
  where activation_codes.id = v_code.id;

  return jsonb_build_object(
    'success', true,
    'course_id', v_course.id,
    'course_title', v_course.title,
    'already_enrolled', v_already_enrolled
  );
end;
$$;

revoke all on function public.generate_activation_codes(uuid, integer, timestamptz) from public;
revoke all on function public.redeem_activation_code(text) from public;
grant execute on function public.generate_activation_codes(uuid, integer, timestamptz) to authenticated;
grant execute on function public.redeem_activation_code(text) to authenticated;

-- ---------- Updated-at triggers ----------
do $$
declare
  t text;
begin
  foreach t in array array['profiles','site_settings','courses','lectures','materials','payments','enrollments','lecture_progress','projects']
  loop
    execute format('drop trigger if exists set_updated_at_%I on public.%I', t, t);
    execute format('create trigger set_updated_at_%I before update on public.%I for each row execute function public.set_updated_at()', t, t);
  end loop;
end $$;

-- ---------- Row Level Security ----------
alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;
alter table public.courses enable row level security;
alter table public.lectures enable row level security;
alter table public.materials enable row level security;
alter table public.payments enable row level security;
alter table public.activation_codes enable row level security;
alter table public.enrollments enable row level security;
alter table public.lecture_progress enable row level security;
alter table public.projects enable row level security;
alter table public.favorites enable row level security;
alter table public.certificates enable row level security;
alter table public.notifications enable row level security;

-- Drop/recreate policies so the script can be safely re-run without deleting data.
do $$
declare r record;
begin
  for r in select schemaname, tablename, policyname from pg_policies where schemaname = 'public'
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end $$;

create policy profiles_select_own_or_admin on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy profiles_update_own_or_admin on public.profiles
for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

create policy site_settings_public_read on public.site_settings
for select to anon, authenticated using (true);
create policy site_settings_admin_all on public.site_settings
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy courses_public_read on public.courses
for select to anon, authenticated
using (published = true or public.is_admin());
create policy courses_admin_all on public.courses
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy lectures_accessible_read on public.lectures
for select to anon, authenticated
using (public.can_access_lecture(id) or public.is_admin());
create policy lectures_admin_all on public.lectures
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy materials_accessible_read on public.materials
for select to anon, authenticated
using (public.can_access_lecture(lecture_id) or public.is_admin());
create policy materials_admin_all on public.materials
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy payments_select_own_or_admin on public.payments
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy payments_insert_own on public.payments
for insert to authenticated with check (user_id = auth.uid());
create policy payments_admin_update on public.payments
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy payments_admin_delete on public.payments
for delete to authenticated using (public.is_admin());

create policy activation_codes_admin_only on public.activation_codes
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy enrollments_select_own_or_admin on public.enrollments
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy enrollments_admin_all on public.enrollments
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy progress_own_all on public.lecture_progress
for all to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

create policy projects_public_approved_or_own on public.projects
for select to anon, authenticated
using (status = 'approved' or user_id = auth.uid() or public.is_admin());
create policy projects_insert_own on public.projects
for insert to authenticated with check (user_id = auth.uid());
create policy projects_update_own_pending_or_admin on public.projects
for update to authenticated
using ((user_id = auth.uid() and status = 'pending') or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());
create policy projects_delete_own_pending_or_admin on public.projects
for delete to authenticated
using ((user_id = auth.uid() and status = 'pending') or public.is_admin());

create policy favorites_own_all on public.favorites
for all to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy certificates_select_own_or_admin on public.certificates
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy certificates_admin_all on public.certificates
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy notifications_own_select on public.notifications
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy notifications_own_update on public.notifications
for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy notifications_admin_all on public.notifications
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Storage buckets ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('public-assets', 'public-assets', true, 10485760, array['image/jpeg','image/png','image/webp','image/svg+xml']),
  ('lecture-videos', 'lecture-videos', false, 1073741824, array['video/mp4','application/vnd.apple.mpegurl','video/mp2t']),
  ('course-materials', 'course-materials', false, 104857600, null),
  ('student-projects', 'student-projects', false, 20971520, array['image/jpeg','image/png','image/webp']),
  ('payment-proofs', 'payment-proofs', false, 10485760, array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage RLS policies.
do $$
declare r record;
begin
  for r in select policyname from pg_policies where schemaname = 'storage' and tablename = 'objects'
  loop
    if r.policyname like 'hunda_%' then
      execute format('drop policy if exists %I on storage.objects', r.policyname);
    end if;
  end loop;
end $$;

create policy hunda_public_assets_read on storage.objects
for select to anon, authenticated
using (bucket_id = 'public-assets');

create policy hunda_admin_storage_all on storage.objects
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy hunda_lecture_videos_read on storage.objects
for select to anon, authenticated
using (bucket_id = 'lecture-videos' and public.can_access_lecture_path(name));

create policy hunda_materials_read on storage.objects
for select to anon, authenticated
using (bucket_id = 'course-materials' and public.can_access_material_path(name));

create policy hunda_student_projects_upload_own on storage.objects
for insert to authenticated
with check (
  bucket_id = 'student-projects'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy hunda_student_projects_read on storage.objects
for select to anon, authenticated
using (
  bucket_id = 'student-projects'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
    or exists (select 1 from public.projects p where p.image_path = name and p.status = 'approved')
  )
);

create policy hunda_student_projects_delete_own on storage.objects
for delete to authenticated
using (
  bucket_id = 'student-projects'
  and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);

create policy hunda_payment_proofs_upload_own on storage.objects
for insert to authenticated
with check (
  bucket_id = 'payment-proofs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy hunda_payment_proofs_read_own_or_admin on storage.objects
for select to authenticated
using (
  bucket_id = 'payment-proofs'
  and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);

-- ---------- Default site content ----------
insert into public.site_settings (id, settings)
values (
  'public',
  jsonb_build_object(
    'siteName', 'hunda design',
    'brandName', 'hunda design',
    'logoUrl', '',
    'footerLogoUrl', '',
    'heroTitle', 'طوّر مهاراتك في التصميم',
    'heroDescription', 'محاضرات عملية ومجتمع يساعدك تبني شغل أقوى.',
    'footerDescription', 'منصة عربية لتعلّم التصميم بشكل عملي.',
    'copyrightText', '© {year} {siteName}. جميع الحقوق محفوظة.',
    'socialLinks', jsonb_build_array(),
    'footerSections', jsonb_build_array()
  )
)
on conflict (id) do nothing;

commit;

-- ============================================================
-- 002_v7_motion_content.sql
-- ============================================================
-- Hunda Design V7 — animated branding and public hero video support
-- Run once in Supabase Dashboard > SQL Editor after 001_initial_schema.sql.

begin;

update storage.buckets
set
  file_size_limit = 52428800,
  allowed_mime_types = array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/svg+xml',
    'video/mp4',
    'video/webm',
    'application/json'
  ]
where id = 'public-assets';

-- The settings column is JSONB, so V7 fields do not require table alterations.
-- Existing settings remain untouched and are merged with application defaults.


create or replace function public.admin_review_payment(
  p_payment_id uuid,
  p_action text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment public.payments%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;

  if p_action not in ('approve', 'reject') then
    raise exception 'Invalid action';
  end if;

  select * into v_payment
  from public.payments
  where id = p_payment_id
  for update;

  if not found then
    raise exception 'Payment not found';
  end if;

  if p_action = 'approve' then
    update public.payments
    set status = 'paid', paid_at = coalesce(paid_at, now()), updated_at = now()
    where id = p_payment_id;

    insert into public.enrollments (user_id, course_id, source, payment_id, active)
    values (v_payment.user_id, v_payment.course_id, 'payment', v_payment.id, true)
    on conflict (user_id, course_id)
    do update set active = true, source = 'payment', payment_id = excluded.payment_id, updated_at = now();
  else
    update public.payments
    set status = 'failed', updated_at = now()
    where id = p_payment_id;
  end if;

  return jsonb_build_object('success', true, 'status', case when p_action = 'approve' then 'paid' else 'failed' end);
end;
$$;

revoke all on function public.admin_review_payment(uuid, text) from public;
grant execute on function public.admin_review_payment(uuid, text) to authenticated;

commit;

-- ============================================================
-- 003_v7_complete_fixes.sql
-- ============================================================
-- Hunda Design V7 Complete — compatibility and media fixes (corrected)
begin;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'public-media',
  'public-media',
  true,
  262144000,
  array[
    'image/gif',
    'image/webp',
    'image/svg+xml',
    'video/webm',
    'video/mp4',
    'video/quicktime'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

update public.site_settings
set settings = jsonb_set(
  settings,
  '{paymentMethods}',
  coalesce(
    settings->'paymentMethods',
    '{"paymob":false,"fawry":false,"paypal":false,"trc20":false}'::jsonb
  ),
  true
)
where id = 'public';

-- The frontend calls admin_set_payment_status.
-- Reuse the payment review logic created by migration 002.
create or replace function public.admin_set_payment_status(
  p_payment_id uuid,
  p_action text
)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select public.admin_review_payment(p_payment_id, p_action);
$$;

revoke all on function public.admin_set_payment_status(uuid, text) from public;
grant execute on function public.admin_set_payment_status(uuid, text) to authenticated;

commit;

-- ============================================================
-- 004_youtube_lecture_sources.sql
-- ============================================================
-- Design Tips / Hunda Design — YouTube lecture playback
-- Safe migration: adds a protected video-source table and keeps all existing lectures/files unchanged.

begin;

create table if not exists public.lecture_video_sources (
  lecture_id uuid primary key references public.lectures(id) on delete cascade,
  provider text not null default 'youtube' check (provider in ('youtube')),
  provider_video_id text not null check (provider_video_id ~ '^[A-Za-z0-9_-]{11}$'),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.lecture_video_sources enable row level security;

drop trigger if exists set_updated_at_lecture_video_sources on public.lecture_video_sources;
create trigger set_updated_at_lecture_video_sources
before update on public.lecture_video_sources
for each row execute function public.set_updated_at();

drop policy if exists lecture_video_sources_admin_all on public.lecture_video_sources;
create policy lecture_video_sources_admin_all
on public.lecture_video_sources
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Authenticated admins need table privileges; RLS still blocks every non-admin direct query.
grant select, insert, update, delete on public.lecture_video_sources to authenticated;
revoke all on public.lecture_video_sources from anon;

create or replace function public.get_lecture_playback(p_lecture_id uuid)
returns table (
  provider text,
  provider_video_id text
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can_access_lecture(p_lecture_id) and not public.is_admin() then
    return;
  end if;

  return query
  select s.provider, s.provider_video_id
  from public.lecture_video_sources s
  where s.lecture_id = p_lecture_id;
end;
$$;

revoke all on function public.get_lecture_playback(uuid) from public;
grant execute on function public.get_lecture_playback(uuid) to anon, authenticated;

comment on table public.lecture_video_sources is
'Protected external video identifiers. Students receive a source only through get_lecture_playback after lecture-access checks.';

commit;

-- ============================================================
-- 005_student_reviews.sql
-- ============================================================
-- Design Tips — student reviews for courses and lectures
-- Run once after 004_youtube_lecture_sources.sql.

begin;

create table if not exists public.student_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  lecture_id uuid references public.lectures(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 3 and 1000),
  reviewer_name text not null default 'طالب في المنصة',
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_reviews_single_target check (
    (course_id is not null and lecture_id is null)
    or (course_id is null and lecture_id is not null)
  )
);

create unique index if not exists student_reviews_one_course_review_per_user
on public.student_reviews (user_id, course_id)
where course_id is not null;

create unique index if not exists student_reviews_one_lecture_review_per_user
on public.student_reviews (user_id, lecture_id)
where lecture_id is not null;

create index if not exists idx_student_reviews_course_created
on public.student_reviews (course_id, created_at desc)
where course_id is not null;

create index if not exists idx_student_reviews_lecture_created
on public.student_reviews (lecture_id, created_at desc)
where lecture_id is not null;

create or replace function public.prepare_student_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_name text;
begin
  if tg_op = 'INSERT' then
    if v_uid is null then
      raise exception 'Authentication required';
    end if;

    if new.user_id is distinct from v_uid and not public.is_admin() then
      raise exception 'You can only submit your own review';
    end if;

    if new.course_id is not null
       and not public.can_access_course(new.course_id)
       and not public.is_admin() then
      raise exception 'Course access is required before reviewing it';
    end if;

    if new.lecture_id is not null
       and not public.can_access_lecture(new.lecture_id)
       and not public.is_admin() then
      raise exception 'Lecture access is required before reviewing it';
    end if;

    select nullif(trim(display_name), '') into v_name
    from public.profiles
    where id = new.user_id;

    new.reviewer_name := coalesce(v_name, 'طالب في المنصة');
    new.comment := trim(new.comment);
    new.is_hidden := false;
  elsif not public.is_admin() then
    if old.user_id is distinct from v_uid then
      raise exception 'You can only edit your own review';
    end if;

    new.user_id := old.user_id;
    new.course_id := old.course_id;
    new.lecture_id := old.lecture_id;
    new.reviewer_name := old.reviewer_name;
    new.is_hidden := old.is_hidden;
    new.comment := trim(new.comment);
  end if;

  return new;
end;
$$;

drop trigger if exists prepare_student_review_trigger on public.student_reviews;
create trigger prepare_student_review_trigger
before insert or update on public.student_reviews
for each row execute function public.prepare_student_review();

drop trigger if exists set_updated_at_student_reviews on public.student_reviews;
create trigger set_updated_at_student_reviews
before update on public.student_reviews
for each row execute function public.set_updated_at();

alter table public.student_reviews enable row level security;

drop policy if exists student_reviews_own_or_admin_read on public.student_reviews;
create policy student_reviews_own_or_admin_read
on public.student_reviews
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists student_reviews_insert_own on public.student_reviews;
create policy student_reviews_insert_own
on public.student_reviews
for insert
to authenticated
with check (
  user_id = auth.uid()
  and (
    (course_id is not null and public.can_access_course(course_id))
    or (lecture_id is not null and public.can_access_lecture(lecture_id))
  )
);

drop policy if exists student_reviews_update_own_or_admin on public.student_reviews;
create policy student_reviews_update_own_or_admin
on public.student_reviews
for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists student_reviews_delete_own_or_admin on public.student_reviews;
create policy student_reviews_delete_own_or_admin
on public.student_reviews
for delete
to authenticated
using (user_id = auth.uid() or public.is_admin());

create or replace function public.get_student_reviews(
  p_course_id uuid default null,
  p_lecture_id uuid default null
)
returns table (
  id uuid,
  rating smallint,
  comment text,
  reviewer_name text,
  is_hidden boolean,
  created_at timestamptz,
  updated_at timestamptz,
  is_own boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.id,
    r.rating,
    r.comment,
    r.reviewer_name,
    r.is_hidden,
    r.created_at,
    r.updated_at,
    (r.user_id = auth.uid()) as is_own
  from public.student_reviews r
  where (
    (
      p_course_id is not null
      and p_lecture_id is null
      and r.course_id = p_course_id
      and exists (
        select 1 from public.courses c
        where c.id = p_course_id
          and (c.published = true or public.can_access_course(c.id) or public.is_admin())
      )
    )
    or (
      p_lecture_id is not null
      and p_course_id is null
      and r.lecture_id = p_lecture_id
      and (public.can_access_lecture(p_lecture_id) or public.is_admin())
    )
  )
  and (r.is_hidden = false or r.user_id = auth.uid() or public.is_admin())
  order by r.created_at desc;
$$;

revoke all on function public.get_student_reviews(uuid, uuid) from public;
grant execute on function public.get_student_reviews(uuid, uuid) to anon, authenticated;

revoke all on public.student_reviews from anon;
grant select, insert, update, delete on public.student_reviews to authenticated;

comment on table public.student_reviews is
'One review per student for each course or lecture. Public review reading is exposed through get_student_reviews without user identifiers.';

commit;

-- ============================================================
-- 006_admin_projects_crud.sql
-- ============================================================
-- Allow admins to create portfolio projects on behalf of students.
-- Existing update/delete policies already allow admins to manage all projects.

drop policy if exists projects_insert_admin on public.projects;
create policy projects_insert_admin on public.projects
for insert to authenticated
with check (public.is_admin());

-- ============================================================
-- 006_admin_reset_password.sql
-- ============================================================
-- Design Tips / Hunda Design — Admin User Management (Reset Password & Delete User)
-- Allows authenticated admins to:
-- 1. Reset/set password directly for any student
-- 2. Delete student account and clean up related records

begin;

-- Function: Reset Student Password
create or replace function public.admin_reset_user_password(
  target_user_id uuid,
  new_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $$
declare
  caller_is_admin boolean;
begin
  caller_is_admin := public.is_admin();
  
  if not caller_is_admin then
    return jsonb_build_object('success', false, 'error', 'غير مصرح: هذه العملية مخصصة للمشرفين فقط.');
  end if;

  if target_user_id is null then
    return jsonb_build_object('success', false, 'error', 'معرف المستخدم غير صحيح.');
  end if;

  if new_password is null or length(trim(new_password)) < 6 then
    return jsonb_build_object('success', false, 'error', 'كلمة المرور يجب أن لا تقل عن 6 أحرف.');
  end if;

  update auth.users
  set encrypted_password = extensions.crypt(new_password, extensions.gen_salt('bf')),
      updated_at = now()
  where id = target_user_id;

  if not found then
    return jsonb_build_object('success', false, 'error', 'المستخدم غير موجود في سجلات الحسابات.');
  end if;

  return jsonb_build_object('success', true, 'message', 'تم تحديث كلمة المرور بنجاح.');
end;
$$;

-- Function: Delete Student Account
create or replace function public.admin_delete_user(
  target_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, extensions, pg_temp
as $$
declare
  caller_is_admin boolean;
  target_role text;
begin
  caller_is_admin := public.is_admin();
  if not caller_is_admin then
    return jsonb_build_object('success', false, 'error', 'غير مصرح: هذه العملية مخصصة للمشرفين فقط.');
  end if;

  if target_user_id is null or target_user_id = auth.uid() then
    return jsonb_build_object('success', false, 'error', 'لا يمكنك حذف حسابك الإداري الحالي.');
  end if;

  select role into target_role from public.profiles where id = target_user_id;
  if target_role = 'admin' then
    return jsonb_build_object('success', false, 'error', 'لا يمكن حذف حساب الأدمن من شاشة الطلاب.');
  end if;

  -- Delete from auth.users (cascades to profiles, enrollments, reviews, etc.)
  delete from auth.users where id = target_user_id;

  return jsonb_build_object('success', true, 'message', 'تم حذف حساب الطالب بنجاح.');
end;
$$;

revoke all on function public.admin_reset_user_password(uuid, text) from public;
grant execute on function public.admin_reset_user_password(uuid, text) to authenticated;

revoke all on function public.admin_delete_user(uuid) from public;
grant execute on function public.admin_delete_user(uuid) to authenticated;

commit;

-- ============================================================
-- 007_project_multi_images.sql
-- ============================================================
-- Multiple images for student projects while keeping legacy single-image columns compatible.

alter table public.projects
  add column if not exists image_paths text[] not null default '{}'::text[],
  add column if not exists image_urls text[] not null default '{}'::text[];

-- Backfill existing projects so old records continue to work with the new UI.
update public.projects
set image_paths = case
      when coalesce(array_length(image_paths, 1), 0) = 0 and nullif(image_path, '') is not null
        then array[image_path]
      else image_paths
    end,
    image_urls = case
      when coalesce(array_length(image_urls, 1), 0) = 0 and nullif(image_url, '') is not null
        then array[image_url]
      else image_urls
    end;

-- Approved public projects must expose every stored project image, not just the legacy cover image.
drop policy if exists hunda_student_projects_read on storage.objects;
create policy hunda_student_projects_read on storage.objects
for select to anon, authenticated
using (
  bucket_id = 'student-projects'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
    or exists (
      select 1
      from public.projects p
      where p.status = 'approved'
        and (
          p.image_path = name
          or name = any(coalesce(p.image_paths, '{}'::text[]))
        )
    )
  )
);

-- ============================================================
-- 008_project_covers_and_student_edit.sql
-- ============================================================
-- Dedicated project covers + safe student editing workflow.
-- Student edits are always returned to pending review; only admins can approve/publish.

begin;

alter table public.projects
  add column if not exists cover_path text,
  add column if not exists cover_url text;

-- Existing projects keep using their first image as the visual fallback until a dedicated cover is uploaded.
update public.projects
set cover_path = coalesce(nullif(cover_path, ''), nullif(image_path, '')),
    cover_url = coalesce(nullif(cover_url, ''), nullif(image_url, ''))
where nullif(cover_path, '') is null;

create or replace function public.enforce_student_project_review_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Admin/service updates retain full moderation control.
  if coalesce(auth.role(), '') = 'service_role' or public.is_admin() then
    return new;
  end if;

  -- A student may only edit their own project and can never transfer ownership.
  if old.user_id is distinct from auth.uid() then
    raise exception 'You can only edit your own project';
  end if;

  new.user_id := old.user_id;
  new.status := 'pending';
  new.reviewed_by := null;
  new.reviewed_at := null;
  new.admin_note := old.admin_note;
  return new;
end;
$$;

drop trigger if exists enforce_student_project_review_state_trigger on public.projects;
create trigger enforce_student_project_review_state_trigger
before update on public.projects
for each row execute function public.enforce_student_project_review_state();

-- Students can revise any of their own projects; the trigger above forces re-review.
drop policy if exists projects_update_own_pending_or_admin on public.projects;
drop policy if exists projects_update_own_or_admin on public.projects;
create policy projects_update_own_or_admin on public.projects
for update to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

-- Approved public projects can read every internal image and any legacy/private cover.
drop policy if exists hunda_student_projects_read on storage.objects;
create policy hunda_student_projects_read on storage.objects
for select to anon, authenticated
using (
  bucket_id = 'student-projects'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin()
    or exists (
      select 1
      from public.projects p
      where p.status = 'approved'
        and (
          p.image_path = name
          or p.cover_path = name
          or name = any(coalesce(p.image_paths, '{}'::text[]))
        )
    )
  )
);

-- Students may upload only their own public project covers.
drop policy if exists hunda_project_covers_upload_own on storage.objects;
create policy hunda_project_covers_upload_own on storage.objects
for insert to authenticated
with check (
  bucket_id = 'public-assets'
  and (storage.foldername(name))[1] = 'project-covers'
  and (storage.foldername(name))[2] = auth.uid()::text
);

-- A student cannot directly remove media from a currently-approved project.
-- The UI updates the project first (trigger => pending), then deletes removed files safely.
drop policy if exists hunda_student_projects_delete_own on storage.objects;
create policy hunda_student_projects_delete_own on storage.objects
for delete to authenticated
using (
  bucket_id = 'student-projects'
  and (
    public.is_admin()
    or (
      (storage.foldername(name))[1] = auth.uid()::text
      and not exists (
        select 1
        from public.projects p
        where p.user_id = auth.uid()
          and p.status = 'approved'
          and (
            p.image_path = name
            or p.cover_path = name
            or name = any(coalesce(p.image_paths, '{}'::text[]))
          )
      )
    )
  )
);

drop policy if exists hunda_project_covers_delete_own on storage.objects;
create policy hunda_project_covers_delete_own on storage.objects
for delete to authenticated
using (
  bucket_id = 'public-assets'
  and (
    public.is_admin()
    or (
      (storage.foldername(name))[1] = 'project-covers'
      and (storage.foldername(name))[2] = auth.uid()::text
      and not exists (
        select 1
        from public.projects p
        where p.user_id = auth.uid()
          and p.status = 'approved'
          and p.cover_path = name
      )
    )
  )
);

commit;

-- ============================================================
-- 009_bunny_stream_sources.sql
-- ============================================================
-- Secure Bunny Stream support for lecture playback.
-- Keeps all existing YouTube and Supabase-storage lecture sources working.

begin;

alter table public.lecture_video_sources
  drop constraint if exists lecture_video_sources_provider_check,
  drop constraint if exists lecture_video_sources_provider_video_id_check;

alter table public.lecture_video_sources
  add constraint lecture_video_sources_provider_check
    check (provider in ('youtube', 'bunny')),
  add constraint lecture_video_sources_provider_video_id_check
    check (
      (provider = 'youtube' and provider_video_id ~ '^[A-Za-z0-9_-]{11}$')
      or
      (provider = 'bunny' and provider_video_id ~ '^[A-Fa-f0-9-]{32,40}$')
    );

comment on column public.lecture_video_sources.provider is
'External video provider. youtube keeps legacy playback; bunny uses server-signed Bunny Stream embeds.';

comment on column public.lecture_video_sources.provider_video_id is
'Provider-specific ID only. Secrets and signed Bunny playback URLs are never stored here.';

commit;

-- ============================================================
-- 010_prevent_invalid_bunny_source_ids.sql
-- ============================================================
begin;

alter table public.lecture_video_sources
  drop constraint if exists lecture_video_sources_bunny_video_not_lecture_id;

alter table public.lecture_video_sources
  add constraint lecture_video_sources_bunny_video_not_lecture_id
  check (
    provider <> 'bunny'
    or provider_video_id <> lecture_id::text
  ) not valid;

comment on constraint lecture_video_sources_bunny_video_not_lecture_id
on public.lecture_video_sources is
'Prevents accidentally storing a Supabase lecture UUID as the Bunny Stream video UUID. Existing rows can be repaired before validating the constraint.';

commit;

-- ============================================================
-- 20260805_activation_code_redeem_fix.sql
-- ============================================================
-- Design Tips — reliable and idempotent activation-code redemption
-- Fixes:
-- 1) A retry by the same student after a successful redemption returns success.
-- 2) Used codes are reported as used instead of the misleading "disabled" message.
-- 3) The function still requires a real authenticated Supabase session.

create or replace function public.redeem_activation_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user uuid := auth.uid();
  v_hash text;
  v_code public.activation_codes%rowtype;
  v_course public.courses%rowtype;
  v_already_enrolled boolean := false;
begin
  if v_user is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(coalesce(p_code, '')), '') is null then
    raise exception 'Invalid activation code';
  end if;

  v_hash := encode(
    digest(public.normalize_activation_code(p_code), 'sha256'),
    'hex'
  );

  select * into v_code
  from public.activation_codes
  where code_hash = v_hash
  for update;

  if not found then
    raise exception 'Invalid activation code';
  end if;

  select * into v_course
  from public.courses
  where id = v_code.course_id;

  if not found or not v_course.published then
    raise exception 'Course is not available';
  end if;

  select exists (
    select 1
    from public.enrollments
    where user_id = v_user
      and course_id = v_code.course_id
      and active = true
  ) into v_already_enrolled;

  -- A mobile/network retry can reach the server after the first redemption
  -- already succeeded. Return success for the same owner instead of an error.
  if v_code.used_at is not null then
    if v_code.used_by = v_user and v_already_enrolled then
      return jsonb_build_object(
        'success', true,
        'course_id', v_course.id,
        'course_title', v_course.title,
        'already_enrolled', true,
        'retried', true
      );
    end if;

    raise exception 'Activation code was already used';
  end if;

  -- A disabled unused code was intentionally stopped by the administration.
  if not v_code.is_active then
    raise exception 'Activation code is disabled';
  end if;

  if v_code.expires_at is not null and v_code.expires_at <= now() then
    raise exception 'Activation code has expired';
  end if;

  insert into public.enrollments (
    user_id,
    course_id,
    source,
    activation_code_id,
    active
  )
  values (
    v_user,
    v_code.course_id,
    'activation_code',
    v_code.id,
    true
  )
  on conflict (user_id, course_id)
  do update set
    active = true,
    source = 'activation_code',
    activation_code_id = excluded.activation_code_id,
    updated_at = now();

  update public.activation_codes
  set
    used_by = v_user,
    used_at = now(),
    is_active = false
  where activation_codes.id = v_code.id;

  return jsonb_build_object(
    'success', true,
    'course_id', v_course.id,
    'course_title', v_course.title,
    'already_enrolled', v_already_enrolled,
    'retried', false
  );
end;
$$;

revoke all on function public.redeem_activation_code(text) from public;
grant execute on function public.redeem_activation_code(text) to authenticated;

-- ============================================================
-- 20260815_activation_code_admin_management.sql
-- ============================================================
-- Design Tips — persistent admin-visible activation codes
-- New activation codes keep their plaintext value for admins only.
-- Existing codes created before this migration cannot be recovered from their hashes.

begin;

alter table public.activation_codes
  add column if not exists code_value text;

comment on column public.activation_codes.code_value is
  'Plain activation code retained for admin-only management. Protected by activation_codes_admin_only RLS policy.';

-- Drop first: later migrations change the parameter defaults, which CREATE OR REPLACE cannot undo.
drop function if exists public.generate_activation_codes(uuid, integer, timestamptz);
create or replace function public.generate_activation_codes(
  p_course_id uuid,
  p_quantity integer default 1,
  p_expires_at timestamptz default null
)
returns table (id uuid, code text, code_preview text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  i integer;
  v_code text;
  v_hash text;
  v_id uuid;
  v_preview text;
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;

  if p_quantity < 1 or p_quantity > 500 then
    raise exception 'Quantity must be between 1 and 500';
  end if;

  if not exists (select 1 from public.courses where courses.id = p_course_id) then
    raise exception 'Course not found';
  end if;

  for i in 1..p_quantity loop
    loop
      v_code := 'HD-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4)) || '-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4));
      v_hash := encode(digest(public.normalize_activation_code(v_code), 'sha256'), 'hex');
      v_preview := 'HD-****-' || right(v_code, 4);

      begin
        insert into public.activation_codes (
          course_id,
          code_hash,
          code_preview,
          code_value,
          expires_at,
          created_by
        )
        values (
          p_course_id,
          v_hash,
          v_preview,
          v_code,
          p_expires_at,
          auth.uid()
        )
        returning activation_codes.id into v_id;
        exit;
      exception when unique_violation then
        -- Extremely unlikely; generate another random code.
      end;
    end loop;

    id := v_id;
    code := v_code;
    code_preview := v_preview;
    return next;
  end loop;
end;
$$;

revoke all on function public.generate_activation_codes(uuid, integer, timestamptz) from public;
grant execute on function public.generate_activation_codes(uuid, integer, timestamptz) to authenticated;

commit;

-- ============================================================
-- 20260817_project_interactions_and_admin_delete.sql
-- ============================================================
-- Design Tips — interactive student projects + safe admin user deletion prerequisites

begin;

-- Keep activation-code audit data valid when an Auth user is deleted.
-- A used code stays disabled and keeps used_at, while used_by may become NULL via ON DELETE SET NULL.
alter table public.activation_codes drop constraint if exists activation_codes_check;
alter table public.activation_codes drop constraint if exists activation_codes_usage_consistency;
alter table public.activation_codes
  add constraint activation_codes_usage_consistency
  check (used_by is null or used_at is not null);

-- Cached counters keep the public gallery fast.
alter table public.projects add column if not exists likes_count integer not null default 0 check (likes_count >= 0);
alter table public.projects add column if not exists saves_count integer not null default 0 check (saves_count >= 0);
alter table public.projects add column if not exists comments_count integer not null default 0 check (comments_count >= 0);
alter table public.projects add column if not exists views_count integer not null default 0 check (views_count >= 0);

-- Project interaction counters are database-managed. The existing student-review
-- trigger must allow trusted counter refreshes without allowing students to spoof them.
create or replace function public.enforce_student_project_review_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_counter_refresh boolean := coalesce(current_setting('app.project_counter_refresh', true), '') = '1';
  v_only_counters_touched boolean :=
    (to_jsonb(new) - array['likes_count','saves_count','comments_count','views_count'])
    = (to_jsonb(old) - array['likes_count','saves_count','comments_count','views_count']);
  v_counters_changed boolean :=
    new.likes_count is distinct from old.likes_count
    or new.saves_count is distinct from old.saves_count
    or new.comments_count is distinct from old.comments_count
    or new.views_count is distinct from old.views_count;
begin
  -- Trusted internal refreshes are allowed even when 0 is rewritten as 0 during backfill,
  -- but they may not modify any non-counter project field.
  if v_counter_refresh then
    if v_only_counters_touched then
      return new;
    end if;
    raise exception 'Internal project counter refresh attempted to change project content';
  end if;

  -- Outside trusted refreshes, nobody can write cached counters directly.
  if v_counters_changed then
    raise exception 'Project interaction counters are managed automatically';
  end if;

  -- Admin/service updates retain full moderation control.
  if coalesce(auth.role(), '') = 'service_role' or public.is_admin() then
    return new;
  end if;

  -- A student may only edit their own project and can never transfer ownership.
  if old.user_id is distinct from auth.uid() then
    raise exception 'You can only edit your own project';
  end if;

  new.user_id := old.user_id;
  new.status := 'pending';
  new.reviewed_by := null;
  new.reviewed_at := null;
  new.admin_note := old.admin_note;
  return new;
end;
$$;

create table if not exists public.project_likes (
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.project_saves (
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.project_comments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  commenter_name text not null default 'طالب في المنصة',
  body text not null check (char_length(trim(body)) between 1 and 800),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_views (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  visitor_id uuid,
  created_at timestamptz not null default now(),
  constraint project_views_one_identity check (num_nonnulls(user_id, visitor_id) = 1)
);

create unique index if not exists project_views_unique_user
  on public.project_views (project_id, user_id)
  where user_id is not null;

create unique index if not exists project_views_unique_visitor
  on public.project_views (project_id, visitor_id)
  where visitor_id is not null;

create index if not exists idx_project_comments_project_created
  on public.project_comments (project_id, created_at desc);
create index if not exists idx_project_likes_user on public.project_likes (user_id);
create index if not exists idx_project_saves_user on public.project_saves (user_id);

create or replace function public.prepare_project_comment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
begin
  if tg_op = 'INSERT' then
    if auth.uid() is null then
      raise exception 'Authentication required';
    end if;

    new.user_id := auth.uid();
    select nullif(trim(display_name), '') into v_name
    from public.profiles
    where id = auth.uid();
    new.commenter_name := coalesce(v_name, 'طالب في المنصة');
  else
    new.project_id := old.project_id;
    new.user_id := old.user_id;
    new.commenter_name := old.commenter_name;
  end if;

  new.body := trim(new.body);
  return new;
end;
$$;

drop trigger if exists prepare_project_comment_trigger on public.project_comments;
create trigger prepare_project_comment_trigger
before insert or update on public.project_comments
for each row execute function public.prepare_project_comment();

drop trigger if exists set_updated_at_project_comments on public.project_comments;
create trigger set_updated_at_project_comments
before update on public.project_comments
for each row execute function public.set_updated_at();

create or replace function public.refresh_project_interaction_counts()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project_id uuid;
begin
  if tg_op = 'DELETE' then
    v_project_id := old.project_id;
  else
    v_project_id := new.project_id;
  end if;

  perform set_config('app.project_counter_refresh', '1', true);

  update public.projects p
  set
    likes_count = (select count(*)::integer from public.project_likes l where l.project_id = v_project_id),
    saves_count = (select count(*)::integer from public.project_saves s where s.project_id = v_project_id),
    comments_count = (select count(*)::integer from public.project_comments c where c.project_id = v_project_id),
    views_count = (select count(*)::integer from public.project_views v where v.project_id = v_project_id)
  where p.id = v_project_id;

  perform set_config('app.project_counter_refresh', '0', true);
  return null;
end;
$$;

drop trigger if exists refresh_project_likes_count on public.project_likes;
create trigger refresh_project_likes_count
after insert or delete on public.project_likes
for each row execute function public.refresh_project_interaction_counts();

drop trigger if exists refresh_project_saves_count on public.project_saves;
create trigger refresh_project_saves_count
after insert or delete on public.project_saves
for each row execute function public.refresh_project_interaction_counts();

drop trigger if exists refresh_project_comments_count on public.project_comments;
create trigger refresh_project_comments_count
after insert or delete on public.project_comments
for each row execute function public.refresh_project_interaction_counts();

drop trigger if exists refresh_project_views_count on public.project_views;
create trigger refresh_project_views_count
after insert or delete on public.project_views
for each row execute function public.refresh_project_interaction_counts();

create or replace function public.register_project_view(
  p_project_id uuid,
  p_visitor_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_rows bigint := 0;
begin
  if not exists (
    select 1 from public.projects
    where id = p_project_id and status = 'approved'
  ) then
    return false;
  end if;

  if v_user_id is not null then
    insert into public.project_views (project_id, user_id)
    values (p_project_id, v_user_id)
    on conflict do nothing;
  else
    if p_visitor_id is null then return false; end if;
    insert into public.project_views (project_id, visitor_id)
    values (p_project_id, p_visitor_id)
    on conflict do nothing;
  end if;

  get diagnostics v_rows = row_count;
  return v_rows > 0;
end;
$$;

-- Backfill counters if this migration is applied to an existing production database.
select set_config('app.project_counter_refresh', '1', true);

update public.projects p set
  likes_count = (select count(*)::integer from public.project_likes l where l.project_id = p.id),
  saves_count = (select count(*)::integer from public.project_saves s where s.project_id = p.id),
  comments_count = (select count(*)::integer from public.project_comments c where c.project_id = p.id),
  views_count = (select count(*)::integer from public.project_views v where v.project_id = p.id);

select set_config('app.project_counter_refresh', '0', true);

alter table public.project_likes enable row level security;
alter table public.project_saves enable row level security;
alter table public.project_comments enable row level security;
alter table public.project_views enable row level security;

drop policy if exists project_likes_select_own_or_admin on public.project_likes;
create policy project_likes_select_own_or_admin on public.project_likes
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists project_likes_insert_own on public.project_likes;
create policy project_likes_insert_own on public.project_likes
for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.projects p
    where p.id = project_id and p.status = 'approved'
  )
);

drop policy if exists project_likes_delete_own_or_admin on public.project_likes;
create policy project_likes_delete_own_or_admin on public.project_likes
for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists project_saves_select_own_or_admin on public.project_saves;
create policy project_saves_select_own_or_admin on public.project_saves
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists project_saves_insert_own on public.project_saves;
create policy project_saves_insert_own on public.project_saves
for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.projects p
    where p.id = project_id and p.status = 'approved'
  )
);

drop policy if exists project_saves_delete_own_or_admin on public.project_saves;
create policy project_saves_delete_own_or_admin on public.project_saves
for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists project_comments_public_read on public.project_comments;
create policy project_comments_public_read on public.project_comments
for select to anon, authenticated
using (
  exists (
    select 1 from public.projects p
    where p.id = project_id and p.status = 'approved'
  )
  or user_id = auth.uid()
  or public.is_admin()
);

drop policy if exists project_comments_insert_own on public.project_comments;
create policy project_comments_insert_own on public.project_comments
for insert to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.projects p
    where p.id = project_id and p.status = 'approved'
  )
);

drop policy if exists project_comments_update_own on public.project_comments;
create policy project_comments_update_own on public.project_comments
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists project_comments_delete_own_or_admin on public.project_comments;
create policy project_comments_delete_own_or_admin on public.project_comments
for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

revoke all on public.project_likes from anon, authenticated;
revoke all on public.project_saves from anon, authenticated;
revoke all on public.project_comments from anon, authenticated;
revoke all on public.project_views from anon, authenticated;

grant select, insert, delete on public.project_likes to authenticated;
grant select, insert, delete on public.project_saves to authenticated;
grant select on public.project_comments to anon, authenticated;
grant insert, update, delete on public.project_comments to authenticated;

revoke all on function public.register_project_view(uuid, uuid) from public;
grant execute on function public.register_project_view(uuid, uuid) to anon, authenticated;

commit;

-- ============================================================
-- 20260817_reviews_repair_and_sales.sql
-- ============================================================
-- Design Tips — repair/reinstall student reviews safely on existing production databases.
-- Re-runnable: creates missing objects and replaces the review RPC/trigger/policies.

begin;

create table if not exists public.student_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  lecture_id uuid references public.lectures(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(trim(comment)) between 3 and 1000),
  reviewer_name text not null default 'طالب في المنصة',
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_reviews_single_target check (
    (course_id is not null and lecture_id is null)
    or (course_id is null and lecture_id is not null)
  )
);

-- Repair partially-created tables from older/manual installs.
alter table public.student_reviews add column if not exists reviewer_name text not null default 'طالب في المنصة';
alter table public.student_reviews add column if not exists is_hidden boolean not null default false;
alter table public.student_reviews add column if not exists created_at timestamptz not null default now();
alter table public.student_reviews add column if not exists updated_at timestamptz not null default now();

create unique index if not exists student_reviews_one_course_review_per_user
  on public.student_reviews (user_id, course_id)
  where course_id is not null;

create unique index if not exists student_reviews_one_lecture_review_per_user
  on public.student_reviews (user_id, lecture_id)
  where lecture_id is not null;

create index if not exists idx_student_reviews_course_created
  on public.student_reviews (course_id, created_at desc)
  where course_id is not null;

create index if not exists idx_student_reviews_lecture_created
  on public.student_reviews (lecture_id, created_at desc)
  where lecture_id is not null;

create or replace function public.prepare_student_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_name text;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if tg_op = 'INSERT' then
    -- The browser can never submit a review on behalf of another account.
    if not public.is_admin() then
      new.user_id := v_uid;
    elsif new.user_id is null then
      new.user_id := v_uid;
    end if;

    if new.course_id is not null
       and not public.can_access_course(new.course_id)
       and not public.is_admin() then
      raise exception 'Course access is required before reviewing it';
    end if;

    if new.lecture_id is not null
       and not public.can_access_lecture(new.lecture_id)
       and not public.is_admin() then
      raise exception 'Lecture access is required before reviewing it';
    end if;

    select nullif(trim(display_name), '') into v_name
    from public.profiles
    where id = new.user_id;

    new.reviewer_name := coalesce(v_name, 'طالب في المنصة');
    new.comment := trim(new.comment);
    new.is_hidden := false;
  elsif not public.is_admin() then
    if old.user_id is distinct from v_uid then
      raise exception 'You can only edit your own review';
    end if;

    -- Students can only change their score/comment.
    new.user_id := old.user_id;
    new.course_id := old.course_id;
    new.lecture_id := old.lecture_id;
    new.reviewer_name := old.reviewer_name;
    new.is_hidden := old.is_hidden;
    new.comment := trim(new.comment);
  end if;

  return new;
end;
$$;

drop trigger if exists prepare_student_review_trigger on public.student_reviews;
create trigger prepare_student_review_trigger
before insert or update on public.student_reviews
for each row execute function public.prepare_student_review();

drop trigger if exists set_updated_at_student_reviews on public.student_reviews;
create trigger set_updated_at_student_reviews
before update on public.student_reviews
for each row execute function public.set_updated_at();

alter table public.student_reviews enable row level security;

drop policy if exists student_reviews_own_or_admin_read on public.student_reviews;
create policy student_reviews_own_or_admin_read
on public.student_reviews
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists student_reviews_insert_own on public.student_reviews;
create policy student_reviews_insert_own
on public.student_reviews
for insert to authenticated
with check (
  user_id = auth.uid()
  and (
    (course_id is not null and public.can_access_course(course_id))
    or (lecture_id is not null and public.can_access_lecture(lecture_id))
  )
);

drop policy if exists student_reviews_update_own_or_admin on public.student_reviews;
create policy student_reviews_update_own_or_admin
on public.student_reviews
for update to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists student_reviews_delete_own_or_admin on public.student_reviews;
create policy student_reviews_delete_own_or_admin
on public.student_reviews
for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

-- Public-safe reader. User ids/emails are never returned.
create or replace function public.get_student_reviews(
  p_course_id uuid default null,
  p_lecture_id uuid default null
)
returns table (
  id uuid,
  rating smallint,
  comment text,
  reviewer_name text,
  is_hidden boolean,
  created_at timestamptz,
  updated_at timestamptz,
  is_own boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.id,
    r.rating,
    r.comment,
    r.reviewer_name,
    r.is_hidden,
    r.created_at,
    r.updated_at,
    coalesce(r.user_id = auth.uid(), false) as is_own
  from public.student_reviews r
  where (
    (
      p_course_id is not null
      and p_lecture_id is null
      and r.course_id = p_course_id
      and exists (
        select 1
        from public.courses c
        where c.id = p_course_id
          and (c.published = true or public.can_access_course(c.id) or public.is_admin())
      )
    )
    or (
      p_lecture_id is not null
      and p_course_id is null
      and r.lecture_id = p_lecture_id
      and exists (
        select 1
        from public.lectures l
        where l.id = p_lecture_id
          and l.published = true
          and (l.is_free = true or public.can_access_lecture(l.id) or public.is_admin())
      )
    )
  )
  and (r.is_hidden = false or r.user_id = auth.uid() or public.is_admin())
  order by r.created_at desc;
$$;

revoke all on function public.get_student_reviews(uuid, uuid) from public;
grant execute on function public.get_student_reviews(uuid, uuid) to anon, authenticated;

revoke all on public.student_reviews from anon;
grant select, insert, update, delete on public.student_reviews to authenticated;

comment on table public.student_reviews is
'One verified review per student for each accessible course or lecture. Public reads are exposed through get_student_reviews without account identifiers.';

commit;

-- ============================================================
-- 20260920_naqla_lifetime_membership.sql
-- ============================================================
-- Naqla — one lifetime membership that unlocks every published course.
-- MUST run last: it replaces admin_review_payment / generate_activation_codes / redeem_activation_code
-- (also defined in 20260805 and 20260815) and needs activation_codes.code_value from 20260815.
-- The date prefix makes it sort after every other migration. Safe to re-run.
--
-- Model:
--   plans        the thing that is sold (today: one lifetime plan)
--   memberships  one row per member; expires_at is NULL for lifetime plans
--   Access       can_access_course() now returns true for an admin, an active
--                per-course enrollment (kept for gifts/legacy), or an active membership.
--                Lectures, materials, video sources and storage policies already call
--                can_access_course(), so they pick the membership up automatically.

begin;

-- ---------- Plans ----------
create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text not null default '',
  price_egp numeric(12,2) not null default 0 check (price_egp >= 0),
  price_usd numeric(12,2) check (price_usd is null or price_usd >= 0),
  price_usdt numeric(12,2) check (price_usdt is null or price_usdt >= 0),
  is_lifetime boolean not null default true,
  duration_days integer check (duration_days is null or duration_days > 0),
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (is_lifetime = true or duration_days is not null)
);

-- ---------- Memberships ----------
create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  plan_id uuid not null references public.plans(id) on delete restrict,
  source text not null default 'manual' check (source in ('payment', 'activation_code', 'manual', 'gift')),
  payment_id uuid references public.payments(id) on delete set null,
  activation_code_id uuid references public.activation_codes(id) on delete set null,
  active boolean not null default true,
  granted_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_memberships_active on public.memberships (user_id) where active = true;

-- ---------- Payments and codes may now target a plan instead of a course ----------
alter table public.payments alter column course_id drop not null;
alter table public.payments add column if not exists plan_id uuid references public.plans(id) on delete restrict;
alter table public.payments drop constraint if exists payments_target_check;
alter table public.payments add constraint payments_target_check check (course_id is not null or plan_id is not null);

alter table public.activation_codes alter column course_id drop not null;
alter table public.activation_codes add column if not exists plan_id uuid references public.plans(id) on delete cascade;
alter table public.activation_codes drop constraint if exists activation_codes_target_check;
alter table public.activation_codes add constraint activation_codes_target_check check (course_id is not null or plan_id is not null);

-- ---------- Track presentation on courses ----------
alter table public.courses add column if not exists accent text check (accent is null or accent in ('pink', 'purple', 'orange', 'teal'));
alter table public.courses add column if not exists sort_order integer not null default 100;

-- ---------- updated_at triggers ----------
drop trigger if exists set_updated_at_plans on public.plans;
create trigger set_updated_at_plans before update on public.plans
for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_memberships on public.memberships;
create trigger set_updated_at_memberships before update on public.memberships
for each row execute function public.set_updated_at();

-- ---------- Access ----------
create or replace function public.has_active_membership(p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select p_user is not null and exists (
    select 1 from public.memberships
    where user_id = p_user
      and active = true
      and (expires_at is null or expires_at > now())
  );
$$;

create or replace function public.can_access_course(p_course_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin()
    or public.has_active_membership(auth.uid())
    or exists (
      select 1 from public.enrollments
      where user_id = auth.uid() and course_id = p_course_id and active = true
    );
$$;

-- ---------- Granting (server-side only) ----------
create or replace function public.grant_membership(
  p_user uuid,
  p_plan uuid,
  p_source text default 'manual',
  p_payment uuid default null,
  p_code uuid default null
)
returns public.memberships
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan public.plans%rowtype;
  v_row public.memberships%rowtype;
begin
  select * into v_plan from public.plans where id = p_plan;
  if not found then
    raise exception 'Plan not found';
  end if;

  insert into public.memberships (user_id, plan_id, source, payment_id, activation_code_id, active, granted_at, expires_at)
  values (
    p_user, p_plan, p_source, p_payment, p_code, true, now(),
    case when v_plan.is_lifetime then null else now() + make_interval(days => v_plan.duration_days) end
  )
  on conflict (user_id) do update
    set plan_id = excluded.plan_id,
        source = excluded.source,
        payment_id = coalesce(excluded.payment_id, public.memberships.payment_id),
        activation_code_id = coalesce(excluded.activation_code_id, public.memberships.activation_code_id),
        active = true,
        granted_at = now(),
        expires_at = excluded.expires_at,
        updated_at = now()
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.grant_membership(uuid, uuid, text, uuid, uuid) from public, anon, authenticated;
grant execute on function public.grant_membership(uuid, uuid, text, uuid, uuid) to service_role;

-- Default plan used by membership codes and manual grants.
create or replace function public.default_plan_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from public.plans where published = true order by created_at asc limit 1;
$$;

-- ---------- Payment review (approve = membership when the payment targets a plan) ----------
create or replace function public.admin_review_payment(
  p_payment_id uuid,
  p_action text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payment public.payments%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;

  if p_action not in ('approve', 'reject') then
    raise exception 'Invalid action';
  end if;

  select * into v_payment from public.payments where id = p_payment_id for update;
  if not found then
    raise exception 'Payment not found';
  end if;

  if p_action = 'approve' then
    update public.payments
    set status = 'paid', paid_at = coalesce(paid_at, now()), updated_at = now()
    where id = p_payment_id;

    if v_payment.plan_id is not null then
      perform public.grant_membership(v_payment.user_id, v_payment.plan_id, 'payment', v_payment.id, null);
    else
      insert into public.enrollments (user_id, course_id, source, payment_id, active)
      values (v_payment.user_id, v_payment.course_id, 'payment', v_payment.id, true)
      on conflict (user_id, course_id)
      do update set active = true, source = 'payment', payment_id = excluded.payment_id, updated_at = now();
    end if;
  else
    update public.payments set status = 'failed', updated_at = now() where id = p_payment_id;
  end if;

  return jsonb_build_object('success', true, 'status', case when p_action = 'approve' then 'paid' else 'failed' end);
end;
$$;

revoke all on function public.admin_review_payment(uuid, text) from public;
grant execute on function public.admin_review_payment(uuid, text) to authenticated;

-- ---------- Activation codes ----------
-- Passing NULL as p_course_id creates membership codes (prefix NQ-).
-- Passing a course id keeps the old single-course behaviour.
create or replace function public.generate_activation_codes(
  p_course_id uuid default null,
  p_quantity integer default 1,
  p_expires_at timestamptz default null
)
returns table (id uuid, code text, code_preview text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  i integer;
  v_code text;
  v_hash text;
  v_id uuid;
  v_preview text;
  v_plan uuid;
  v_prefix text;
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;

  if p_quantity < 1 or p_quantity > 500 then
    raise exception 'Quantity must be between 1 and 500';
  end if;

  if p_course_id is null then
    v_plan := public.default_plan_id();
    if v_plan is null then
      raise exception 'No published plan found';
    end if;
    v_prefix := 'NQ';
  else
    if not exists (select 1 from public.courses where courses.id = p_course_id) then
      raise exception 'Course not found';
    end if;
    v_prefix := 'HD';
  end if;

  for i in 1..p_quantity loop
    loop
      v_code := v_prefix || '-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4)) || '-' || upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 4));
      v_hash := encode(digest(public.normalize_activation_code(v_code), 'sha256'), 'hex');
      v_preview := v_prefix || '-****-' || right(v_code, 4);

      begin
        insert into public.activation_codes (course_id, plan_id, code_hash, code_preview, code_value, expires_at, created_by)
        values (p_course_id, v_plan, v_hash, v_preview, v_code, p_expires_at, auth.uid())
        returning activation_codes.id into v_id;
        exit;
      exception when unique_violation then
        -- Extremely unlikely; generate another random code.
      end;
    end loop;

    id := v_id;
    code := v_code;
    code_preview := v_preview;
    return next;
  end loop;
end;
$$;

revoke all on function public.generate_activation_codes(uuid, integer, timestamptz) from public;
grant execute on function public.generate_activation_codes(uuid, integer, timestamptz) to authenticated;

create or replace function public.redeem_activation_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user uuid := auth.uid();
  v_hash text;
  v_code public.activation_codes%rowtype;
  v_course public.courses%rowtype;
  v_plan public.plans%rowtype;
  v_already boolean := false;
begin
  if v_user is null then
    raise exception 'Authentication required';
  end if;

  if nullif(trim(coalesce(p_code, '')), '') is null then
    raise exception 'Invalid activation code';
  end if;

  v_hash := encode(digest(public.normalize_activation_code(p_code), 'sha256'), 'hex');

  select * into v_code from public.activation_codes where code_hash = v_hash for update;
  if not found then
    raise exception 'Invalid activation code';
  end if;

  -- Membership code
  if v_code.plan_id is not null then
    select * into v_plan from public.plans where id = v_code.plan_id;
    if not found or not v_plan.published then
      raise exception 'Plan is not available';
    end if;

    v_already := public.has_active_membership(v_user);

    if v_code.used_at is not null then
      if v_code.used_by = v_user and v_already then
        return jsonb_build_object('success', true, 'kind', 'membership', 'plan_title', v_plan.title, 'already_enrolled', true, 'retried', true);
      end if;
      raise exception 'Activation code was already used';
    end if;

    if not v_code.is_active then raise exception 'Activation code is disabled'; end if;
    if v_code.expires_at is not null and v_code.expires_at <= now() then raise exception 'Activation code has expired'; end if;

    perform public.grant_membership(v_user, v_plan.id, 'activation_code', null, v_code.id);

    update public.activation_codes
    set used_by = v_user, used_at = now(), is_active = false
    where activation_codes.id = v_code.id;

    return jsonb_build_object('success', true, 'kind', 'membership', 'plan_title', v_plan.title, 'already_enrolled', v_already, 'retried', false);
  end if;

  -- Single-course code (legacy behaviour)
  select * into v_course from public.courses where id = v_code.course_id;
  if not found or not v_course.published then
    raise exception 'Course is not available';
  end if;

  select exists (
    select 1 from public.enrollments
    where user_id = v_user and course_id = v_code.course_id and active = true
  ) into v_already;

  if v_code.used_at is not null then
    if v_code.used_by = v_user and v_already then
      return jsonb_build_object('success', true, 'kind', 'course', 'course_id', v_course.id, 'course_title', v_course.title, 'already_enrolled', true, 'retried', true);
    end if;
    raise exception 'Activation code was already used';
  end if;

  if not v_code.is_active then raise exception 'Activation code is disabled'; end if;
  if v_code.expires_at is not null and v_code.expires_at <= now() then raise exception 'Activation code has expired'; end if;

  insert into public.enrollments (user_id, course_id, source, activation_code_id, active)
  values (v_user, v_code.course_id, 'activation_code', v_code.id, true)
  on conflict (user_id, course_id)
  do update set active = true, source = 'activation_code', activation_code_id = excluded.activation_code_id, updated_at = now();

  update public.activation_codes
  set used_by = v_user, used_at = now(), is_active = false
  where activation_codes.id = v_code.id;

  return jsonb_build_object('success', true, 'kind', 'course', 'course_id', v_course.id, 'course_title', v_course.title, 'already_enrolled', v_already, 'retried', false);
end;
$$;

revoke all on function public.redeem_activation_code(text) from public;
grant execute on function public.redeem_activation_code(text) to authenticated;

-- ---------- Admin: grant / revoke by email ----------
create or replace function public.admin_grant_membership(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid;
  v_plan uuid;
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;

  select id into v_user from public.profiles where lower(email) = lower(trim(p_email));
  if v_user is null then
    raise exception 'User not found';
  end if;

  v_plan := public.default_plan_id();
  if v_plan is null then
    raise exception 'No published plan found';
  end if;

  perform public.grant_membership(v_user, v_plan, 'manual', null, null);
  return jsonb_build_object('success', true, 'user_id', v_user);
end;
$$;

create or replace function public.admin_set_membership_active(p_user uuid, p_active boolean)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Admin permission required';
  end if;

  update public.memberships set active = p_active, updated_at = now() where user_id = p_user;
  return jsonb_build_object('success', true, 'active', p_active);
end;
$$;

revoke all on function public.admin_grant_membership(text) from public;
revoke all on function public.admin_set_membership_active(uuid, boolean) from public;
grant execute on function public.admin_grant_membership(text) to authenticated;
grant execute on function public.admin_set_membership_active(uuid, boolean) to authenticated;

-- ---------- RLS ----------
alter table public.plans enable row level security;
alter table public.memberships enable row level security;

drop policy if exists plans_public_read on public.plans;
create policy plans_public_read on public.plans
for select to anon, authenticated
using (published = true or public.is_admin());

drop policy if exists plans_admin_all on public.plans;
create policy plans_admin_all on public.plans
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists memberships_select_own_or_admin on public.memberships;
create policy memberships_select_own_or_admin on public.memberships
for select to authenticated using (user_id = auth.uid() or public.is_admin());

drop policy if exists memberships_admin_all on public.memberships;
create policy memberships_admin_all on public.memberships
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- Seed: one plan and the three tracks ----------
-- The price below is a placeholder. Change it from the admin portal (Plan page).
insert into public.plans (slug, title, description, price_egp, is_lifetime, published)
values (
  'naqla-lifetime',
  'عضوية نقلة مدى الحياة',
  'دفعة واحدة تفتح لك الكورسات الثلاثة، وأي كورس نضيفه لاحقًا.',
  1999,
  true,
  true
)
on conflict (slug) do nothing;

insert into public.courses (title, description, price, published, featured, accent, sort_order)
select v.title, v.description, 0, true, v.featured, v.accent, v.sort_order
from (values
  ('تصميم المحتوى الجرافيكي', 'ابنِ هوية بصرية لمحتواك: من فكرة الشريحة والبوستر إلى غلاف الكورس والإعلان، بأدوات عملية وخطوات واضحة.', true, 'pink', 10),
  ('بناء المنصات بالـ Vibe Coding', 'اصنع منصتك ومنتجك الرقمي بنفسك بمساعدة الذكاء الاصطناعي، من غير ما تكون مبرمج.', false, 'purple', 20),
  ('الإعلانات الممولة', 'اعرف تستهدف العميل المناسب لك، وتبني حملة تجيب نتيجة وتقيس أثرها.', false, 'orange', 30)
) as v(title, description, featured, accent, sort_order)
where not exists (select 1 from public.courses c where c.title = v.title);

commit;

-- ============================================================
-- 20260926_profile_guard_and_admin_bootstrap.sql
-- ============================================================
-- Naqla: profile guard fix. Safe to re-run.
--
-- 1) Bootstrap: supabase/scripts/make_admin.sql failed in the SQL Editor with
--    "Only an admin can change user roles", because the editor sends no JWT and the
--    old guard only trusted service_role. A request with no JWT role is a direct
--    database connection (SQL Editor, psql), which only the project owner has.
--    Every API request (anon or signed-in) always carries a role claim.
-- 2) Hardening: a signed-in user could change their own is_active (a disabled admin
--    could re-enable themselves) and their own email copy in profiles (used by
--    admin_grant_membership to find users). Both are now admin-only, like role.
--    handle_new_user() still syncs email from auth.users: it runs inside the Auth
--    service, which uses service_role or no JWT.

begin;

create or replace function public.prevent_role_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text := nullif(auth.role(), '');
begin
  if v_role is null or v_role = 'service_role' or public.is_admin() then
    return new;
  end if;

  if new.role is distinct from old.role then
    raise exception 'Only an admin can change user roles';
  end if;

  if new.is_active is distinct from old.is_active then
    raise exception 'Only an admin can change account status';
  end if;

  if new.email is distinct from old.email then
    raise exception 'Email is managed by the sign-in account';
  end if;

  return new;
end;
$$;

drop trigger if exists prevent_role_escalation_trigger on public.profiles;
create trigger prevent_role_escalation_trigger
before update on public.profiles
for each row execute function public.prevent_role_escalation();

commit;
